package genwrite

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// RenderPlan prints the Terraform-style preview: one line per target,
// action first, then the path, then why. Conflicts render as
// "overwrite?" — their fate is decided during Apply.
func RenderPlan(w io.Writer, plan *Plan) {
	fmt.Fprintf(w, "Plan for %s (%d file(s))\n", plan.Root, len(plan.Ops))
	width := 0
	for _, op := range plan.Ops {
		if len(op.Path) > width {
			width = len(op.Path)
		}
	}
	for _, op := range plan.Ops {
		action := op.Decision.String()
		if op.Conflict {
			action = "overwrite?"
		}
		why := op.Why
		if op.Reason != "" && op.Decision == DecisionCreate {
			why = op.Reason
		}
		fmt.Fprintf(w, "  %-11s %-*s  %s\n", action, width, op.Path, why)
	}
}

// RenderResult prints the one-line-per-category outcome summary.
func RenderResult(w io.Writer, res *Result) {
	line := func(label string, paths []string) {
		if len(paths) == 0 {
			return
		}
		fmt.Fprintf(w, "  %-11s %s\n", label, strings.Join(SortedPaths(paths), ", "))
	}
	line("created", res.Created)
	line("regenerated", res.Regenerated)
	line("overwritten", res.Overwritten)
	line("appended", res.Appended)
	line("unchanged", res.Unchanged)
	line("skipped", res.Skipped)
	if len(res.SkippedConflicts) > 0 {
		fmt.Fprintf(w, "  %d conflict(s) left in place — re-run with --force to overwrite\n", len(res.SkippedConflicts))
	}
	if res.Aborted {
		fmt.Fprintln(w, "  aborted — remaining files untouched")
	}
}

// PromptResolver returns a Resolve func that runs the interactive
// conflict prompt on the given reader/writer pair:
//
//	k8s/gitops/web/stages.yaml was generated by sandboxctl but has been edited.
//	  [s]kip (keep your version)  [o]verwrite  [d]iff  [a]ll-skip  [q]uit
//
// Enter defaults to skip — the destructive choice is never the default.
// EOF or a read error resolves to skip so a closed stdin can't wedge or
// destroy anything.
func PromptResolver(in io.Reader, out io.Writer) func(Conflict) Choice {
	reader := bufio.NewReader(in)
	return func(c Conflict) Choice {
		fmt.Fprintf(out, "\n%s was generated by sandboxctl but has been edited.\n", c.Path)
		for {
			fmt.Fprint(out, "  [s]kip (keep your version)  [o]verwrite  [d]iff  [a]ll-skip  [q]uit: ")
			line, err := reader.ReadString('\n')
			if err != nil && line == "" {
				fmt.Fprintln(out, "skip (input closed)")
				return ChoiceSkip
			}
			switch strings.ToLower(strings.TrimSpace(line)) {
			case "", "s", "skip":
				return ChoiceSkip
			case "o", "overwrite":
				return ChoiceOverwrite
			case "d", "diff":
				if c.Diff == "" {
					fmt.Fprintln(out, "  (no textual difference — likely line endings or the marker line)")
				} else {
					fmt.Fprintln(out, c.Diff)
				}
			case "a", "all", "all-skip":
				return ChoiceSkipAll
			case "q", "quit", "abort":
				return ChoiceAbort
			default:
				fmt.Fprintln(out, "  please answer s, o, d, a, or q")
			}
			if err != nil {
				// A read error after a partial line: bail safely.
				return ChoiceSkip
			}
		}
	}
}
